Repository AY2324S2-CS2103T-F11-3/tp, pull requests merged in 2024-04, with the labels that each got.

#142 Add JUnit tests for saving, listing and deleting of interviews
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteInterviewCommand.java
  src/main/java/seedu/address/logic/parser/AddInterviewCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteInterviewCommandParser.java
  src/test/java/seedu/address/logic/commands/DeleteInterviewCommandTest.java
  src/test/java/seedu/address/logic/commands/ListInterviewsCommandTest.java
  src/test/java/seedu/address/logic/parser/AddInterviewCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteInterviewCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedInterviewTest.java
  src/test/java/seedu/address/testutil/InterviewBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalInterviews.java
Labels: type.Task, priority.High

#136 Implement and test computation and display of overall statistics
  src/main/java/seedu/address/logic/commands/AddInterviewCommand.java
  src/main/java/seedu/address/logic/commands/ViewOverallStatisticsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/ViewOverallStatisticsCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Epic, priority.Medium

#143 Update UserGuide
  docs/UserGuide.md
Labels: type.Task, priority.High

#147 Update UserGuide for status, filter, view statistics
  docs/UserGuide.md
  docs/images/applicantStatusAddExample.png
  docs/images/viewOverallStatisticsExample.png
Labels: type.Task, priority.High

#150 Update UserGuide.md to include filtering of interviews by date
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#152 Final patches to UG before v1.3 release
  docs/UserGuide.md
  docs/images/addInterviewExample.png
Labels: type.Task, priority.High

#153 Final patches to UG before v1.3 release
  docs/UserGuide.md
Labels: type.Bug, severity.Low

#234 Fix bugs in AddInterviewCommand
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddInterviewCommand.java
  src/test/java/seedu/address/model/interview/InterviewTest.java
  src/test/java/seedu/address/testutil/InterviewBuilder.java
Labels: type.Bug

#239 Fix typo in message usage
  src/main/java/seedu/address/logic/commands/AddApplicantPersonCommand.java
  src/main/java/seedu/address/logic/commands/AddInterviewerPersonCommand.java
  src/main/java/seedu/address/logic/commands/AddPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddInterviewerCommandParser.java
  src/test/java/seedu/address/logic/parser/AddInterviewerCommandParserTest.java
Labels: type.Bug, severity.Medium

#237 Fix bug with duplicate persons check
  src/main/java/seedu/address/logic/commands/AddApplicantPersonCommand.java
  src/main/java/seedu/address/logic/commands/AddInterviewerPersonCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddApplicantCommandTest.java
  src/test/java/seedu/address/logic/commands/AddInterviewerCommandTest.java
Labels: type.Bug, severity.Medium

#236 Remedy code-related bug-fixes for status
  src/main/java/seedu/address/logic/commands/AddInterviewerStatusCommand.java
  src/main/java/seedu/address/logic/commands/FilterPersonsByStatusCommand.java
  src/main/java/seedu/address/logic/parser/AddApplicantStatusCommandParser.java
  src/main/java/seedu/address/logic/parser/AddInterviewerStatusCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Applicant.java
  src/test/java/seedu/address/logic/commands/AddInterviewerStatusCommandTest.java
  src/test/java/seedu/address/logic/parser/AddApplicantStatusCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddInterviewerStatusCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Bug, severity.Medium

#240 Edit UG for Help, AddInterview, AddApplicant and AddInterviewer commands
  docs/UserGuide.md
  docs/img.png
  docs/img_1.png
  docs/img_2.png
Labels: priority.High, severity.Medium, type.DocumentationBug

#241 Update UserGuide after PE-D
  docs/UserGuide.md
  docs/images/find-command/base.png
  docs/images/find-command/findnamesuccess.png
  docs/images/find-command/multiplekeywords.png
  docs/images/find-command/nomatches.png
Labels: type.Enhancement, severity.VeryLow, severity.Low, type.DocumentationBug

#242 Edit UG errors
  docs/UserGuide.md
Labels: type.DocumentationBug

#243 Remove Edit command and Changed Delete Person Command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/interview/Interview.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Bug, severity.High

#244 Remove deliberate tagging functionality and update UserGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/AddApplicantCommandParser.java
  src/main/java/seedu/address/logic/parser/AddInterviewerCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddApplicantCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddInterviewerCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium

#245 Update HelpWindow to include clear command
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Bug, priority.Low

#246 Fix UG status bugs, overhaul UG format, revert illegal mod in filter status
  docs/UserGuide.md
  docs/images/addApplicantStatusExample.png
  docs/images/addInterviewerStatusExample.png
  docs/images/applicantStatusAddExample.png
  docs/images/deleteInterviewerStatusExample.png
  docs/images/tetherOrientation.png
  src/main/java/seedu/address/logic/commands/FilterPersonsByStatusCommand.java
  src/main/java/seedu/address/model/person/Person.java
Labels: severity.Medium, type.DocumentationBug

#247 Remove unnecessary code parts
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddApplicantPersonCommand.java
  src/main/java/seedu/address/logic/commands/AddInterviewerPersonCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddApplicantCommandTest.java
  src/test/java/seedu/address/logic/commands/AddInterviewerCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: type.Bug, severity.Medium

#248 Revert illegal v1.4 modification
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/parser/AddApplicantCommandParser.java
  src/main/java/seedu/address/logic/parser/AddApplicantStatusCommandParser.java
  src/main/java/seedu/address/logic/parser/AddInterviewCommandParser.java
  src/main/java/seedu/address/logic/parser/AddInterviewerCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteInterviewCommandParser.java
  src/main/java/seedu/address/logic/parser/FilterPersonsByStatusCommandParser.java
  src/main/java/seedu/address/logic/parser/FindEmailCommandParser.java
  src/main/java/seedu/address/logic/parser/FindNameCommandParser.java
  src/main/java/seedu/address/logic/parser/FindPhoneCommandParser.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/test/java/seedu/address/logic/parser/AddApplicantCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddApplicantStatusCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddInterviewCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddInterviewerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteInterviewCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FilterPersonsByStatusCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindEmailCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindNameCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindPhoneCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
Labels: severity.Medium, type.FunctionalityBug

#250 Update PPP
  docs/AboutUs.md
  docs/team/yashpola.md
  docs/team/yashwit.md
Labels: type.Task, priority.Low

#251 Modify UserGuide
  docs/UserGuide.md
Labels: type.Enhancement, priority.High

#252 Add PPP
  docs/team/ryanchiang.md
Labels: type.Task, priority.Low

#253 Minor edits to UG
  docs/UserGuide.md
Labels: type.Enhancement, priority.High

#254 Update filtering interviews by date section on UserGuide.md
  docs/UserGuide.md
Labels: type.Enhancement, priority.Medium

#255 Update PPP filename and theme for site
  docs/AboutUs.md
  docs/site.json
  docs/team/macareonie.md
Labels: type.Task, priority.Medium

#260 Update UG
  docs/UserGuide.md
Labels: type.Task, priority.High

#262 Update UserGuide.md to fix bugs
  docs/UserGuide.md
Labels: type.Bug, priority.High

#266 Edit DG
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#267 Rephrase sections in UG
  docs/UserGuide.md
  docs/images/find-command/base_to_multiplesuccess.png
  docs/images/find-command/base_to_success.png
Labels: type.Task, priority.Medium

#268 Update UserGuide.md and DeveloperGuide.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task, priority.High

#269 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/add-status/StatusCommandClasses.puml
  docs/diagrams/add-status/StatusCommandSequence.puml
Labels: type.Task, priority.High

#270 Update UG
  docs/UserGuide.md
Labels: type.Task, priority.High

#274 Update DeveloperGuide.md and UserGuide.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task, priority.High

#275 Update DeveloperGuide.md to fix spacing issues
  docs/DeveloperGuide.md
Labels: type.Bug, priority.High

#277 Update PPP
  docs/team/yashpola.md
Labels: type.Task, priority.High

#278 Update Ui.png
  docs/images/Ui.png
Labels: type.Task, priority.Low
