Repository AY2324S2-CS2103T-F11-3/tp, pull requests merged in 2024-03, with the labels that each got.

#17 Update use cases and NFRs in Developer Guide for v1.1
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#18 Edit UserGuide.md to include features from our own project
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#35 Fix nits for v1.1
  docs/AboutUs.md
  docs/images/zhikaiong2001.png
Labels: type.Bug

#46 Add Applicant type
  src/main/java/seedu/address/logic/commands/AddApplicantCommand.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddApplicantCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/person/Applicant.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddApplicantCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddApplicantCommandTest.java
  src/test/java/seedu/address/logic/parser/AddApplicantCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Story, type.Task, priority.High

#45 Modify Delete type
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: type.Story, type.Task, priority.High

#47 Add Interviewer type
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddInterviewerCommand.java
  src/main/java/seedu/address/logic/parser/AddInterviewerCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/person/Interviewer.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddInterviewerCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddInterviewerCommandTest.java
  src/test/java/seedu/address/logic/parser/AddInterviewerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Story, type.Task, priority.High

#50 Create Interview Class and Respective classes related to Interview
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddApplicantPersonCommand.java
  src/main/java/seedu/address/logic/commands/AddInterviewerPersonCommand.java
  src/main/java/seedu/address/logic/commands/AddPersonCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddApplicantCommandParser.java
  src/main/java/seedu/address/logic/parser/AddInterviewerCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/interview/Interview.java
  src/main/java/seedu/address/model/interview/UniqueInterviewList.java
  src/main/java/seedu/address/model/interview/exceptions/DuplicateInterviewException.java
  src/main/java/seedu/address/model/interview/exceptions/InterviewNotFoundException.java
  src/main/java/seedu/address/model/person/Interviewer.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddApplicantCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddApplicantCommandTest.java
  src/test/java/seedu/address/logic/commands/AddInterviewerCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddInterviewerCommandTest.java
  src/test/java/seedu/address/logic/parser/AddApplicantCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddInterviewerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High

#51 Implement Add Interview command and Parsing
  src/main/java/seedu/address/logic/commands/AddInterviewCommand.java
  src/main/java/seedu/address/logic/parser/AddInterviewCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
Labels: type.Task, priority.High

#52 Add DeleteInterviewCommand and the parser for it
  src/main/java/seedu/address/logic/commands/DeleteInterviewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteInterviewCommandParser.java
Labels: priority.High

#56 Resolve checkstyle violations
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddInterviewCommand.java
  src/main/java/seedu/address/logic/commands/DeleteInterviewCommand.java
  src/main/java/seedu/address/logic/parser/AddApplicantCommandParser.java
  src/main/java/seedu/address/logic/parser/AddInterviewCommandParser.java
  src/main/java/seedu/address/logic/parser/AddInterviewerCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteInterviewCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/interview/Interview.java
  src/main/java/seedu/address/model/interview/UniqueInterviewList.java
  src/main/java/seedu/address/model/interview/exceptions/DuplicateInterviewException.java
  src/main/java/seedu/address/model/interview/exceptions/InterviewNotFoundException.java
Labels: type.Task

#58 Fix small checkstyle issue
  src/main/java/seedu/address/logic/commands/ListInterviewsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: type.Task

#65 Resolve bugs caused by refactoring
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddApplicantCommandTest.java
  src/test/java/seedu/address/logic/commands/AddInterviewerCommandTest.java
  src/test/java/seedu/address/logic/parser/AddInterviewerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Bug, priority.High

#70 Modify construction of persons from hard drive storage
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Applicant.java
  src/main/java/seedu/address/model/person/Interviewer.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Type.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: type.Task, type.Bug, priority.High

#71 Check against duplicate phone numbers when adding persons to Tether
  src/main/java/seedu/address/logic/commands/AddApplicantPersonCommand.java
  src/main/java/seedu/address/logic/commands/AddInterviewerPersonCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddApplicantCommandTest.java
  src/test/java/seedu/address/logic/commands/AddInterviewerCommandTest.java
Labels: type.Task, priority.Medium

#68 Branch interview exceptions tests
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddInterviewCommand.java
  src/main/java/seedu/address/logic/commands/DeleteInterviewCommand.java
  src/main/java/seedu/address/model/interview/Interview.java
  src/main/java/seedu/address/model/interview/exceptions/DuplicateInterviewException.java
  src/main/java/seedu/address/model/interview/exceptions/InterviewNotFoundException.java
  src/main/java/seedu/address/model/person/exceptions/PersonNotFoundException.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddInterviewCommandIntergrationTest.java
  src/test/java/seedu/address/logic/commands/AddInterviewCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/testutil/InterviewBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#72 Minor Fixes
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddInterviewCommandIntergrationTest.java
Labels: priority.High

#75 Create exceptions for incorrect phone numbers for AddInterviewCommand
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddInterviewCommand.java
  src/test/java/seedu/address/logic/commands/AddInterviewCommandIntergrationTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#79 Docs and minor changes
  build.gradle
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
  docs/images/UpdatedUi.png
  docs/images/tether_logo.png
  docs/site.json
  docs/team/jiangbowei.md
  docs/team/ryanchiang.md
  docs/team/wesleyyu.md
  docs/team/yashwit.md
  docs/team/zhikaiong2001.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/AddApplicantPersonCommand.java
  src/main/java/seedu/address/logic/commands/AddInterviewCommand.java
  src/main/java/seedu/address/logic/commands/AddInterviewerPersonCommand.java
  src/main/java/seedu/address/logic/commands/AddPersonCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/model/interview/Interview.java
  src/main/java/seedu/address/model/person/Applicant.java
  src/main/java/seedu/address/model/person/Interviewer.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/tether_logo.png
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/AddApplicantCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddInterviewerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story, type.Task, type.Bug, priority.High

#80 Add a brief help summary in help window for easier reference
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: type.Story, type.Enhancement, priority.High

#84 Add saving functionality for interviews
  src/main/java/seedu/address/logic/commands/ListInterviewsCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/storage/JsonAdaptedInterview.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
Labels: type.Task, priority.High

#81 Update Sequence diagrams
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
Labels: type.Task, priority.High

#82 Update Class diagrams for model package
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Task, priority.High

#85 Update StorageClassDiagram.puml UML diagram
  docs/diagrams/StorageClassDiagram.puml
Labels: type.Task, priority.High

#86 Edit Class Diagrams for BetterModelClassDiagram
  docs/diagrams/BetterModelClassDiagram.puml
Labels: priority.High

#88 Add UniqueInterviewList and Interview to ModelClassDiagram
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Task, priority.High

#87 Update README for v1.2
  README.md
Labels: type.Task, priority.Low

#92 Add status tagging for applicants and interviewers
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddApplicantStatusCommand.java
  src/main/java/seedu/address/logic/commands/AddInterviewerStatusCommand.java
  src/main/java/seedu/address/logic/parser/AddApplicantCommandParser.java
  src/main/java/seedu/address/logic/parser/AddApplicantStatusCommandParser.java
  src/main/java/seedu/address/logic/parser/AddInterviewerCommandParser.java
  src/main/java/seedu/address/logic/parser/AddInterviewerStatusCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/person/Applicant.java
  src/main/java/seedu/address/model/person/ApplicantStatus.java
  src/main/java/seedu/address/model/person/Interviewer.java
  src/main/java/seedu/address/model/person/InterviewerStatus.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Status.java
  src/main/java/seedu/address/model/person/enums/ApplicantState.java
  src/main/java/seedu/address/model/person/enums/InterviewerState.java
  src/main/java/seedu/address/model/person/enums/Type.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/InterviewBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Story, priority.High

#97 Add junit tests for status type and modify status implementation
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddApplicantStatusCommand.java
  src/main/java/seedu/address/logic/commands/AddInterviewerStatusCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddApplicantStatusCommandParser.java
  src/main/java/seedu/address/logic/parser/AddInterviewerStatusCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/ApplicantStatus.java
  src/main/java/seedu/address/model/person/InterviewerStatus.java
  src/main/java/seedu/address/model/person/Status.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddApplicantStatusCommandTest.java
  src/test/java/seedu/address/logic/commands/AddInterviewerStatusCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddApplicantStatusCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddInterviewerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddInterviewerStatusCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#98 Add status extensions
  src/main/java/seedu/address/logic/commands/AddInterviewCommand.java
  src/main/java/seedu/address/logic/commands/DeleteInterviewCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddApplicantCommandParser.java
  src/main/java/seedu/address/model/person/Applicant.java
  src/main/java/seedu/address/model/person/Interviewer.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/enums/ApplicantState.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/test/java/seedu/address/logic/commands/AddApplicantStatusCommandTest.java
  src/test/java/seedu/address/logic/commands/AddInterviewerStatusCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/InterviewBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Story, type.Enhancement, priority.Low

#101 Add status extensions [E3]
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FilterInterviewsByDateCommand.java
  src/main/java/seedu/address/logic/commands/FilterPersonsByStatusCommand.java
  src/main/java/seedu/address/logic/commands/ListInterviewsCommand.java
  src/main/java/seedu/address/logic/parser/FilterPersonsByStatusCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Status.java
  src/test/java/seedu/address/logic/commands/AddInterviewCommandIntergrationTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FilterInterviewsByDateCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterPersonsByStatusCommandTest.java
  src/test/java/seedu/address/logic/parser/FilterPersonsByStatusCommandParserTest.java
Labels: type.Story, type.Enhancement, priority.Low

#103 Update Developer Guide for v1.3
  docs/DeveloperGuide.md
  docs/diagrams/find/FindCommandClass.puml
  docs/diagrams/find/FindSequenceDiagram-Logic.puml
Labels: type.Task, priority.High

#104 Update Developer Guide for v1.3
  docs/DeveloperGuide.md
  docs/diagrams/add-status/StatusCommandClasses.puml
  docs/diagrams/add-status/StatusCommandSequence.puml
  src/main/java/seedu/address/model/person/Status.java
Labels: type.Task, priority.High

#113 Add logging in AddInterviewCommandParser.java
  src/main/java/seedu/address/logic/parser/AddInterviewCommandParser.java
Labels: type.Enhancement, priority.Low

#112 Update FilterInterviewByDateCommand.java to show the filtered list in the GUI
  src/main/java/seedu/address/logic/commands/FilterInterviewsByDateCommand.java
  src/main/java/seedu/address/ui/InterviewListPanel.java
Labels: type.Task, priority.High

#114 Edit DG
  docs/DeveloperGuide.md
Labels: type.Task

#116 Resize GUI box sizes and Font
  src/main/resources/view/InterviewListCard.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: type.Task, priority.High

#120 Implement automatic sorting for Interviews by date and time
  src/main/java/seedu/address/logic/commands/AddInterviewCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/interview/UniqueInterviewList.java
  src/test/java/seedu/address/logic/commands/AddApplicantCommandTest.java
  src/test/java/seedu/address/logic/commands/AddInterviewerCommandTest.java
Labels: type.Task, priority.High

#122 Write add interview feature for DG
  docs/DeveloperGuide.md
Labels: priority.High

#121 Fix remark bug, touch up cosmetics for dg and application
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/AddApplicantStatusCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/ui/InterviewCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/InterviewListCard.fxml
  src/main/resources/view/InterviewListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
Labels: type.Bug, severity.High

#123 Update DeveloperGuide.md to include saving's implementation
  docs/DeveloperGuide.md
  docs/diagrams/saving/SavingInterviewsAndPersonsSequence.puml
Labels: type.Task, priority.High

#126 GUI and Bug fixes pre-1.3.trial release
  README.md
  build.gradle
  docs/DeveloperGuide.md
  docs/diagrams/add-interviews/AddInterviewCommandSequence.puml
  docs/images/UpdatedUi.png
  docs/index.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/InterviewListCard.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: type.Enhancement, type.Bug, priority.Medium, severity.High

#130 Fix activation bars of sequence diagram
  docs/diagrams/saving/SavingInterviewsAndPersonsSequence.puml
Labels: type.Bug, priority.High

#131 Add class diagrams to list and delete commands part of the DG
  docs/DeveloperGuide.md
  docs/diagrams/delete/DeleteCommandsClassDiagram.puml
  docs/diagrams/list/ListCommandsClassDiagram.puml
Labels: priority.High

#132 Fix GUI
  src/main/resources/view/PersonListCard.fxml
Labels: type.Bug, severity.Medium

#133 Status patches [READ DESCRIPTION FOR PATCH NOTES]
  src/main/java/seedu/address/logic/commands/AddApplicantStatusCommand.java
  src/main/java/seedu/address/logic/commands/AddInterviewCommand.java
  src/main/java/seedu/address/logic/commands/AddInterviewerStatusCommand.java
  src/main/java/seedu/address/logic/commands/DeleteInterviewCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/DeleteInterviewCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/interview/Interview.java
  src/main/java/seedu/address/model/person/Applicant.java
  src/main/java/seedu/address/model/person/ApplicantStatus.java
  src/main/java/seedu/address/model/person/Interviewer.java
  src/main/java/seedu/address/model/person/InterviewerStatus.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Enhancement, type.Bug, severity.High
